apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: default
spec:
  rules:
    - host: local.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-api-service
                port:
                  number: 80
            