apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: akinben/user-service:latest
        imagePullPolicy: Always
        env:
          - name: REDEPLOY_APP
            value: 'REPLACE_BUILD'
          - name: PORT
            value: '3023'
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: api-deployment-secret
                key: node_env
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: api-deployment-secret
                key: db_uri
        command: ["npm","start"]
        ports:
        - containerPort: 3023
        readinessProbe:
          httpGet: 
            path: /health
            port: 3023
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 10m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  type: ClusterIP
  selector:
    app: user-api
  ports:
    - port: 80
      targetPort: 3023
