apiVersion: v1
kind: Secret
metadata:
  name: kube-deployment-secret
type: Opaque
data:
  # echo -n "api-user-1234" | base64
  init.username: YXBpLXVzZXItMTIzNA==
  # echo -n "password1234" | base64
  init.password: cGFzc3dvcmQxMjM0