apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
data:
  mongo-user.sh: |
    mongo admin -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} <<EOF
        use kubesetup_db
        db.createUser({user: "api-user-1234", pwd: "${SECOND_USER_DB_PASSWORD}", roles: [
            { role: "readWrite", db: "kubesetup_db" }
        ]});
    EOF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-key

data:
  mongodb.key: |
    mIt9WmEbjlkKfq8bxhBq62Z7OzApe2HBuJKTscV72bk9zFnvrgMPrOjen9FOs48H6NyNpKNsveVlec4BnO96kDiLFrzKQI2jtkha9G8sPoGIFrazzsys2BZS
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-scripts
data:
  mongodb-data-dir-permission.sh: |
    chown -R mongodb:mongodb ${MONGO_DATA_DIR}
    cp -r /var/lib/mongodbKeyTemp /var/lib/mongodbkey
    chown -R mongodb:mongodb /var/lib/mongodbkey
    chmod 400 /var/lib/mongodbkey/mongodb.key
    chown -R mongodb:mongodb /var/lib/mongodbkey/mongodb.key