---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-account
  namespace: 'default'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-role
rules:
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["deployments"]
  verbs: ["list", "watch"]
- apiGroups: ["*"]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get","list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb-role-binding
subjects:
- kind: ServiceAccount
  name: mongodb-account
  namespace: 'default'
roleRef:
  kind: ClusterRole
  name: mongodb-role
  apiGroup: rbac.authorization.k8s.io